use_frameworks!

target 'KenticoCloud_Example' do
  pod 'KenticoCloud', :path => '../'
  pod 'AlamofireImage', '~> 3.1'

  target 'KenticoCloud_Tests' do
    inherit! :search_paths
    pod 'KenticoCloud', :path => '../'
    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 7.0.2'
    
  end
end

