use_frameworks!

target 'KenticoCloud_Example' do
  pod 'KenticoCloud', :path => '../'
  pod 'AlamofireImage', '~> 3.1'
  pod 'FAPanels'

  target 'KenticoCloud_Tests' do
    inherit! :search_paths

    
  end
end

